import Head from 'next/head'
import React from "react";
import {useState, useEffect} from 'react';
import axios from "axios"
import Link from 'next/link';
import 'bootstrap/dist/css/bootstrap.css';
import { Container,CardGroup, Card, Col, Row, Badge, Button, Grid} from 'reactstrap';
import Image from 'react-bootstrap/Image';

const defaultEndpoint = "https://rickandmortyapi.com/api/character";

export async function getServerSideProps() {

	try{
	
		const res = await axios.get(defaultEndpoint)
  
        	return {
  
        		props:{
				data:res.data
               		}
        	}
	}  catch (error){

		if(error.res){
				
			console.error(error);
			console.error('status', error.res.status);
			console.error('data', error.res.data);
		}

		return{

			notFound: true
		}
	}

}	
 
export default function Home({data}) {

	const { info, results: defaultResults = [] }  = data;
	const [results, updateResults] = useState(defaultResults);
	const [page, updatePage] = useState({
		
		...info,
		current: defaultEndpoint
	}); 
	
	const { current } = page;

	useEffect(() => {
		
		if ( current === defaultEndpoint ) return;

		async function request() {
			
			const res = await axios.get(current);
			const nextData = res.current;

			updatePage({
				
				current,
				...nextData.info
			});

	if (!nextData.info?.prev){
				
				updateResults(nextData.results);
				return;
			}

			updateResults(prev => {
				
				return [
					...prev,
					...nextData.results
				]

			});
		}

		request();
	}, [current]);

	function handleMore(){
		
		updatePage(prev => {
		
			return {
				...prev,
				current: page?.next
			}
		});
	}
	
	return (
    		<>
      		 <Head>
        	  <title>Rick & Morty</title>
                  <meta name="description" content="Generated by create next app" />
        	  <link rel="icon" href="/favicon.ico" />
      		 </Head>	
      		 <Container fluid>	
		  <Row>
		   <Col className="col text-center">
		    <p className="h1 text-primary">Meet the Characters!!!</p>
		   </Col>
		  </Row>
		  <Row xs="2" md="3" lg="4">
		   {results.map(result => {
			   const {id, name, image, status, origin } = result;
			   return (
			    <Col key={id} className="p-3 bg-dark border text-center" fluid="true">
			     <Link href="/character/[id]" as={`/character/${id}`} >	   
			      <a href="" style={{textDecoration:'inherit'}}>
			       <Image src = {image} alt={`${name} Thumbnail`} className="img-fluid"/> 	   
		              <p className="h5 text-info" fluid="fluid"> {name} </p>
			      <p className="h5 text-danger"> Alive? </p>		   
			      <p className="mb-0 text-secondary"> {status} </p>	   
			      <p className="h5 text-info"> From: </p>	   
			      <p className="mb-0 text-secondary" fluid="true"> {origin.name} </p>	   
			      </a>	   
		             </Link>
		            </Col>
			   )
		     })
		   }
		 </Row>
		<Row>
		 <Col className="col text-center">
		 <Button className="text-capitalize" color="primary" size="lg" onClick={handleMore}> See More</Button> 
		 </Col>
		</Row>
		</Container>
    	        </>
      
       );
}

