import Head from 'next/head'
import React from 'react';
import {useState, useEffect} from 'react';
import Link from 'next/link';
import axios from "axios";
import 'bootstrap/dist/css/bootstrap.css';
import {Container, Card, CardImg, Navbar, NavbarBrand, Row, Col} from 'reactstrap';
import Stack from 'react-bootstrap/Stack';
import Image from 'react-bootstrap/Image';

const defaultEndpoint = "https://rickandmortyapi.com/api/character";

export async function getServerSideProps({query}) {
	
	try{
		const {id} = query;
		const res = await axios.get(`${defaultEndpoint}/${id}`);
  
        	return {
  
        		props:{
				data:res.data
               		}
        	}

	} catch (error){

		if(error.res){
				
			console.error(error);
			console.error('status', error.res.status);
			console.error('data', error.res.data);
		}

		return{
			notFound: true
		}	 
	}
	
}
  
export default function Character({data, er}) {
	
	const {name, status, species, type, gender, origin, location, image, created} = data;
	
	return (
    		<>
      		 <Head>
        	  <title>Characters Description</title>
                  <meta name="description" content="Generated by create next app" />
        	  <link rel="icon" href="/favicon.ico" />
      		 </Head>	
		 <Navbar className="my-2" color="light" width="10%">   
		  <NavbarBrand href="/">
		   <Image src ="https://rickandmortyapi.com/api/character/avatar/19.jpeg" alt="" className="rounded-circle" width="10%"/> 
		  </NavbarBrand>
		 </Navbar>
		 <Container className="bg-dark text-center" fluid>
		  <p className="h5 text-light"> Personal Details</p>
		  <p className="h5 text-light">{name}</p> 
                  <img alt="" src={image} className="rounded-0" width="31%"/>
		  <ul>
		   <Stack gap="3">
		   <li><p className="h5 text-secondary">Status:</p></li>
		   <li><p className="h5 text-secondary">{status}</p></li>
		   <li><p className="h5 text-secondary">Species:</p></li>
		   <li><p className="h5 text-secondary">{species}</p></li>
		   <li><p className="h5 text-secondary">Type:</p></li>
		   <li><p className="h5 text-secondary">{type}</p></li>
		   <li><p className="h5 text-secondary">Gender:</p></li>
		   <li><p className="h5 text-secondary">{gender}</p></li>
		   <li><p className="h5 text-secondary">Original From:</p></li>
		   <li><p className="h5 text-secondary">{origin.name}</p></li>
		   <li><p className="h5 text-secondary">Last time seen in:</p></li>
		   <li><p className="h5 text-secondary">{location.name}</p></li>
		   <li><p className="h5 text-secondary">Created:</p></li>
		   <li><p className="h5 text-secondary">{created}</p></li>
		   </Stack>
		  </ul>
		 </Container> 
    	        </>
      
       );
}

